### ISSUE TITLE
facing Hydration error on main page i.e page.tsx of app anybody has a soln for that?

### ISSUE THREAD

**Issue by bhrigu-verma** [webprodigies/corinna-ai#3]
Hydration error

**Comment by anjumann** [comment]
Try adding this line in rootlayout file 

<html lang="en" suppressHydrationWarning>

here  **suppressHydrationWarning** help in suppressing the warning 
@bhrigu-verma

**Comment by Stipex-Hq** [comment]
Yeah there is an issue with the hydration error.

**Comment by bhrigu-verma** [comment]
ok thnaks
